// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// ConleySE
Rcpp::List ConleySE(arma::colvec res, arma::mat W_meat, arma::mat dist, double cutoff, int kernel);
RcppExport SEXP _SpatialEffect_ConleySE(SEXP resSEXP, SEXP W_meatSEXP, SEXP distSEXP, SEXP cutoffSEXP, SEXP kernelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec >::type res(resSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type W_meat(W_meatSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type dist(distSEXP);
    Rcpp::traits::input_parameter< double >::type cutoff(cutoffSEXP);
    Rcpp::traits::input_parameter< int >::type kernel(kernelSEXP);
    rcpp_result_gen = Rcpp::wrap(ConleySE(res, W_meat, dist, cutoff, kernel));
    return rcpp_result_gen;
END_RCPP
}
// DistanceCalculation
Rcpp::List DistanceCalculation(arma::colvec x_coord, arma::colvec y_coord, int metric);
RcppExport SEXP _SpatialEffect_DistanceCalculation(SEXP x_coordSEXP, SEXP y_coordSEXP, SEXP metricSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec >::type x_coord(x_coordSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type y_coord(y_coordSEXP);
    Rcpp::traits::input_parameter< int >::type metric(metricSEXP);
    rcpp_result_gen = Rcpp::wrap(DistanceCalculation(x_coord, y_coord, metric));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SpatialEffect_ConleySE", (DL_FUNC) &_SpatialEffect_ConleySE, 5},
    {"_SpatialEffect_DistanceCalculation", (DL_FUNC) &_SpatialEffect_DistanceCalculation, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_SpatialEffect(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
