// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// ConleySE
arma::mat ConleySE(arma::colvec res, arma::mat X_mat, arma::colvec x_coord, arma::colvec y_coord, double cutoff, int metric);
RcppExport SEXP _SpatialEffect_ConleySE(SEXP resSEXP, SEXP X_matSEXP, SEXP x_coordSEXP, SEXP y_coordSEXP, SEXP cutoffSEXP, SEXP metricSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec >::type res(resSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X_mat(X_matSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type x_coord(x_coordSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type y_coord(y_coordSEXP);
    Rcpp::traits::input_parameter< double >::type cutoff(cutoffSEXP);
    Rcpp::traits::input_parameter< int >::type metric(metricSEXP);
    rcpp_result_gen = Rcpp::wrap(ConleySE(res, X_mat, x_coord, y_coord, cutoff, metric));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SpatialEffect_ConleySE", (DL_FUNC) &_SpatialEffect_ConleySE, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_SpatialEffect(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
