# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ConleySE <- function(res, X_mat, x_coord, y_coord, cutoff, metric) {
    .Call(`_SpatialEffect_ConleySE`, res, X_mat, x_coord, y_coord, cutoff, metric)
}

