# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ConleySE <- function(res, W_meat, dist, cutoff, kernel) {
    .Call(`_SpatialEffect_ConleySE`, res, W_meat, dist, cutoff, kernel)
}

DistanceCalculation <- function(x_coord, y_coord, metric) {
    .Call(`_SpatialEffect_DistanceCalculation`, x_coord, y_coord, metric)
}

